### ISSUE TITLE
전체 CSS 크기 및 간격 수정

### ISSUE THREAD

**Issue by constantly-dev** [mju-likelion/custard-pudding#102]
## 💡Description
전체 CSS 크기 및 간격 수정

## ✅ Tasks
- [x] 버튼 크기 수정
- [x] 지원하기/확인 페이지 텍스트 크기 수정
- [x] 메인 페이지 타이틀 크기 수정
- [x] 404 페이지 레이아웃 수정
