### ISSUE TITLE
지원 페이지 반응형 구현

### ISSUE THREAD

**Issue by zelkovaria** [mju-likelion/custard-pudding#11]
## 💡Description
Apply, Check 페이지 반응형 구현

## ✅ Tasks
- [x] Apply 페이지의 Input 컴포넌트 반응형 구현
  - [x] Catpion
  - [x] StyledInput
  - [x] ErrorMessage
- [x] Check 페이지의 Input 컴포넌트 반응형 구현
  - [x] Catpion
  - [x] StyledInput
  - [x] ErrorMessage
- [x] Check 페이지의 CardBody, CardString 반응형 변경
- [x] SubTitle 컴포넌트 반응형 구현
