### ISSUE TITLE
유효성 검사 적용

### ISSUE THREAD

**Issue by zelkovaria** [mju-likelion/custard-pudding#16]
## 💡Description
input 유효성 검사

## ✅ Tasks
- [x] Check페이지 input 유효성 검사
- [x] Apply페이지 input 유효성 검사
- [x] Caption 내용 아이디->학번
- [x] 유효성검사 아이디 형식->학번 형식
