### ISSUE TITLE
redirect 기능 구현

### ISSUE THREAD

**Issue by zelkovaria** [mju-likelion/custard-pudding#31]
## 💡Description
동작에 알맞는 redirect 구현

## ✅ Tasks
- [x] 지원하기 버튼 클릭 시 지원서 작성 페이지 이동
- [x] 지원 확인 후 알맞은 상태별 페이지 이동
- [x] 세션 스토리지 저장
- [x] 저장되는 학번을 암호화
