### ISSUE TITLE
지원이력 확인 결과 표시

### ISSUE THREAD

**Issue by hyunyeee** [mju-likelion/custard-pudding#39]
## 💡Description
지원 여부 결과 표시

## ✅ Tasks
- [x] API 요청 로직 리팩토링
- [x] 지원 여부 확인 결과 렌더링
- [x] 이미 지원 이력이 있는 경우 작성하지 못하도록 한다
