### ISSUE TITLE
지원서 작성 페이지 제출 버튼 구현

### ISSUE THREAD

**Issue by constantly-dev** [mju-likelion/custard-pudding#56]
## 💡Description
지원서 작성 페이지 제출하기 버튼 구현

## ✅ Tasks
- [ ] 반응형 구현
- [ ] 세션 스토리지 item 삭제
- [ ] form 제출하기 post api 연결
- [ ] file post api 연결
- [ ] type submit 설정
