### ISSUE TITLE
지원 페이지 관련 학생증 구현

### ISSUE THREAD

**Issue by zelkovaria** [mju-likelion/custard-pudding#7]
## 💡Description
지원하기, 지원 확인을 위한 학생증 구현

## ✅ Tasks
- [x] 학생증 svg 추가
- [x] Input 컴포넌트 만들기
- [x] SubTitle 컴포넌트 만들기
- [x] 카드 부분 UI 디자인
- [x] 버튼 컴포넌트 배치
- [x] 지원하기 페이지 학생증 구현
