### ISSUE TITLE
OG 설정

### ISSUE THREAD

**Issue by zelkovaria** [mju-likelion/custard-pudding#70]
## 💡Description
사이트의 og를 설정

## ✅ Tasks
- [ ] og:title : 콘텐츠 제목
- [ ] og:url : 웹페이지 url
- [ ] og:type : 웹페이지 타입
- [ ] og:image : 이미지 URL
- [ ] og:description : 웹페이지에 대한 간단한 설명
